name: webide_splitter
description: A splitter component for Angular Dart
version: 1.5.5
homepage: https://github.com/tejainece/webide_splitter
author: Ravi Teja Gudapati <tejainece@gmail.com>
documentation:

environment:
  sdk: '>=1.24.0 <2.0.0'

dependencies:
  angular: ^4.0.0
  angular_components: ^0.6.0
  dart_to_js_script_rewriter: ^1.0.1

dev_dependencies:
  angular_test: ^1.0.0
  browser: ^0.10.0
  test: ^0.12.0

transformers:
- angular:
    entry_points:
      - web/horizontal/main.dart
      - web/nested/main.dart
      - web/vertical/main.dart
- test/pub_serve:
    $include: test/**_test.dart
- dart_to_js_script_rewriter

# Uncomment the following in sdk 1.24+ to make pub serve
# use dartdevc (webdev.dartlang.org/tools/dartdevc).
web:
  compiler:
    debug: dartdevc
